version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - cot_pdfupload_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: journals
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: secret
  web:
    depends_on:
      - db
    image: gorilych/cot-pdfupload
    ports:
      - "10000:8080"
    volumes:
      - cot_pdfupload_upload_dir:/root/upload
    environment:
      DBSRV: db:3306
      DBNAME: journals
      DBUSER: dbuser
      DBUSERPWD: secret
volumes:
  cot_pdfupload_db_data:
  cot_pdfupload_upload_dir:

